const $ = (selector) => document.querySelector(selector);
const storageKey = 'ea-hiring-role';
const defaults = { title: 'Executive Assistant', arrangement: 'Remote', type: 'Full-time', location: 'South Africa', hours: '40 hours / week', description: '', skills: ['Calendar management', 'Inbox management'], showPay: true, minRate: '8', maxRate: '12' };
const read = () => ({ ...defaults, ...(JSON.parse(localStorage.getItem(storageKey) || '{}')) });
const write = (patch) => { const next = { ...read(), ...patch }; localStorage.setItem(storageKey, JSON.stringify(next)); return next; };
const text = (value) => (value || '').trim();
function toast(message) { const el = $('#toast'); if (!el) return; el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2200); }
function rate(role) { return role.showPay ? `$${role.minRate} – $${role.maxRate} / hour` : 'Rate on request'; }
function hydratePreview() {
  const role = read();
  document.querySelectorAll('[data-preview="title"],[data-review="title"]').forEach(el => el.textContent = role.title || defaults.title);
  document.querySelectorAll('[data-preview="type"],[data-review="type"]').forEach(el => el.textContent = role.type);
  document.querySelectorAll('[data-preview="location"],[data-review="location"]').forEach(el => el.textContent = `${role.arrangement} · ${role.location}`);
  document.querySelectorAll('[data-review="hours"]').forEach(el => el.textContent = role.hours);
  document.querySelectorAll('[data-preview="description"],[data-review="description"]').forEach(el => el.textContent = role.description || 'Add a description so candidates can understand the role before they apply.');
  document.querySelectorAll('[data-preview="rate"],[data-review="rate"]').forEach(el => el.textContent = rate(role));
  document.querySelectorAll('[data-preview="skills"],[data-review="skills"]').forEach(el => el.innerHTML = role.skills.map(skill => `<span>${skill}</span>`).join(''));
}
function bindSaveButton() { $('.save-button')?.addEventListener('click', () => toast('Draft saved')); }
function bindDetails() {
  const form = $('#detailsForm'); if (!form) return; const role = read();
  ['title','arrangement','type','location','hours'].forEach(id => { const input = $(`#${id}`); input.value = role[id] || input.value; input.addEventListener('input', () => { write({ [id]: input.value }); hydratePreview(); }); input.addEventListener('change', () => { write({ [id]: input.value }); hydratePreview(); }); });
  form.addEventListener('submit', event => { event.preventDefault(); if (!text($('#title').value)) { $('#title').focus(); toast('Add a job title to continue'); return; } write({ title: $('#title').value, arrangement: $('#arrangement').value, type: $('#type').value, location: $('#location').value, hours: $('#hours').value }); location.href = './responsibilities.html'; });
}
function bindResponsibilities() {
  const form = $('#responsibilitiesForm'); if (!form) return; let role = read(); const description = $('#description'); description.value = role.description; $('#descriptionCount').textContent = description.value.length;
  const renderSkills = () => { role = read(); $('#skillList').innerHTML = role.skills.map(skill => `<button class="skill" type="button">${skill}<span>×</span></button>`).join(''); hydratePreview(); };
  description.addEventListener('input', () => { $('#descriptionCount').textContent = description.value.length; write({ description: description.value }); hydratePreview(); });
  $('#writeDescription').addEventListener('click', () => { description.value = 'We are looking for an Executive Assistant to provide day-to-day support to a senior leader. You will manage calendars, coordinate meetings, organise travel, and keep priorities on track.\n\nThe right person is organised, professional, comfortable working independently, and confident communicating with internal and external contacts.'; $('#descriptionCount').textContent = description.value.length; write({ description: description.value }); hydratePreview(); toast('Example description added'); });
  const addSkill = () => { const value = text($('#skillInput').value); if (!value) return; const skills = read().skills; if (!skills.some(skill => skill.toLowerCase() === value.toLowerCase())) write({ skills: [...skills, value] }); $('#skillInput').value = ''; renderSkills(); };
  $('#addSkill').addEventListener('click', addSkill); $('#skillInput').addEventListener('keydown', event => { if (event.key === 'Enter') { event.preventDefault(); addSkill(); } });
  $('#skillList').addEventListener('click', event => { const item = event.target.closest('.skill'); if (!item) return; write({ skills: read().skills.filter(skill => skill !== item.childNodes[0].textContent.trim()) }); renderSkills(); });
  form.addEventListener('submit', event => { event.preventDefault(); if (!text(description.value)) { description.focus(); toast('Add a job description to continue'); return; } location.href = './compensation.html'; }); renderSkills();
}
function bindCompensation() {
  const form = $('#compensationForm'); if (!form) return; const role = read(); ['minRate','maxRate'].forEach(id => { $(`#${id}`).value = role[id]; $(`#${id}`).addEventListener('input', event => { write({ [id]: event.target.value }); hydratePreview(); }); }); $('#showPay').checked = role.showPay; $('#showPay').addEventListener('change', event => { write({ showPay: event.target.checked }); hydratePreview(); }); form.addEventListener('submit', event => { event.preventDefault(); if (+$('#minRate').value > +$('#maxRate').value) { toast('The minimum rate must be lower than the maximum'); return; } write({ minRate: $('#minRate').value, maxRate: $('#maxRate').value, showPay: $('#showPay').checked }); location.href = './review.html'; });
}
function bindPublish() { $('#publishJob')?.addEventListener('click', () => { write({ published: true }); location.href = './published.html'; }); }
function bindApplicants() {
  const candidates = [...document.querySelectorAll('.candidate')]; if (!candidates.length) return; const setCandidate = (button) => { const [name, role, experience, skills] = button.dataset.candidate.split('|'); candidates.forEach(item => item.classList.toggle('active', item === button)); $('#profileInitials').textContent = name.split(' ').map(word => word[0]).join(''); $('#profileName').textContent = name; $('#profileRole').textContent = `${role} · ${experience}`; $('#profileSkills').innerHTML = skills.split(',').map(skill => `<span>${skill}</span>`).join(''); $('.match').textContent = button.querySelector('i').textContent + ' match'; }; candidates.forEach(button => button.addEventListener('click', () => setCandidate(button))); $('#shortlist')?.addEventListener('click', () => { $('#shortlist').textContent = 'Shortlisted ✓'; toast('Candidate moved to Shortlisted'); });
}
bindSaveButton(); hydratePreview(); bindDetails(); bindResponsibilities(); bindCompensation(); bindPublish(); bindApplicants();

const jobBoard = [
  {id:'aster',company:'Aster & Co.',initial:'A',title:'Executive Assistant to CEO',arrangement:'Remote',type:'Full-time',location:'South Africa',pay:'$10–$14 / hour',posted:'2 days ago',description:'Aster & Co. is looking for an experienced Executive Assistant to keep the CEO organised and help the leadership team move quickly. This is a hands-on role for someone who enjoys bringing order to a busy day.',responsibilities:['Manage a complex CEO calendar and protect focus time','Prepare meeting briefs, notes, and follow-up actions','Coordinate domestic and international travel','Handle professional communication with clients and partners'],skills:['Calendar management','Executive support','Travel coordination','Google Workspace']},
  {id:'bright',company:'BrightHouse',initial:'B',title:'Senior Executive Assistant',arrangement:'Hybrid',type:'Full-time',location:'Cape Town',pay:'$12–$16 / hour',posted:'3 days ago',description:'Support two founders at a growing professional-services company. You will be the person who keeps decisions, meetings, and key relationships moving forward.',responsibilities:['Coordinate leadership schedules and off-sites','Own travel, expenses, and meeting logistics','Track company priorities and follow-ups','Support internal communications'],skills:['Microsoft Office','Project coordination','Expense management','Written communication']},
  {id:'harbor',company:'Harbor Health',initial:'H',title:'Executive Assistant — Operations',arrangement:'Remote',type:'Contract',location:'South Africa',pay:'$11–$15 / hour',posted:'5 days ago',description:'Harbor Health needs an organised assistant to support its operations lead during a period of growth. The work is structured, varied, and focused on making the team more efficient.',responsibilities:['Maintain operational calendars and reporting deadlines','Schedule stakeholder meetings','Create simple process documents','Manage the shared inbox'],skills:['Inbox management','Notion','Meeting coordination','Process documentation']},
  {id:'mosaic',company:'Mosaic Studio',initial:'M',title:'Part-time Executive Assistant',arrangement:'Remote',type:'Part-time',location:'South Africa',pay:'$9–$12 / hour',posted:'1 week ago',description:'A part-time role supporting a creative director with administrative organisation, client follow-up, and weekly planning.',responsibilities:['Organise the weekly schedule','Prepare client meeting notes','Follow up on actions and invoices','Keep files and contacts current'],skills:['Calendar management','Client communication','Attention to detail','Asana']}
];
function renderJobs(filter = '') { const root = $('#jobResults'); if (!root) return; const matches = jobBoard.filter(job => `${job.title} ${job.company} ${job.skills.join(' ')}`.toLowerCase().includes(filter.toLowerCase())); $('#resultCount').textContent = matches.length; root.innerHTML = matches.map(job => `<a class="job-card" href="./job-detail.html?job=${job.id}"><div class="job-card-top"><div class="job-company">${job.initial}</div><div><h2>${job.title}</h2><p class="company-name">${job.company}</p></div><span class="posted">${job.posted}</span></div><div class="job-tags"><span>${job.arrangement}</span><span>${job.type}</span><span>${job.location}</span></div><p>${job.description}</p><div class="job-card-footer"><b>${job.pay}</b><span>View job →</span></div></a>`).join('') || '<p class="no-results">No roles match that search.</p>'; }
function bindJobs() { if (!$('#jobResults')) return; renderJobs(); $('#searchJobs').addEventListener('click', () => renderJobs($('#jobSearch').value)); $('#jobSearch').addEventListener('input', event => renderJobs(event.target.value)); }
function bindJobDetail() { if (!$('#detailTitle')) return; const id = new URLSearchParams(location.search).get('job'); const job = jobBoard.find(item => item.id === id) || jobBoard[0]; $('#detailInitial').textContent = job.initial; $('#detailCompany').textContent = job.company; $('#detailTitle').textContent = job.title; $('#detailArrangement').textContent = job.arrangement; $('#detailEmployment').textContent = job.type; $('#detailLocation').textContent = job.location; $('#detailPay').textContent = job.pay; $('#detailDescription').textContent = job.description; $('#detailResponsibilities').innerHTML = job.responsibilities.map(item => `<li>${item}</li>`).join(''); $('#detailSkills').innerHTML = job.skills.map(item => `<span>${item}</span>`).join(''); $('#showApplication').addEventListener('click', () => { location.href = `./candidate-signup.html?job=${encodeURIComponent(job.id)}`; }); }
bindJobs(); bindJobDetail();
